[phases.setup]
nixPkgs = [
  "python311",
  "python311Packages.pip",
  "python311Packages.setuptools",
  "python311Packages.wheel",
  "ffmpeg",
  "libGL",
  "libGLU",
  "fontconfig",
  "dejavu_fonts",
  "freetype",
  "libjpeg",
  "zlib"
]

[phases.install]
cmds = [
  "pip install --no-cache-dir --prefix=$NIXPACKS_PATH -r requirements.txt"
]

[start]
cmd = "gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 300 --preload"